### ISSUE TITLE
Spring Security

### ISSUE THREAD

**Issue by ViliqnVachev** [luchob/pathfinder#1]
Здравейте, карах курсът Java web през септември 2021 и сега се оптивам да си направя един проект, но имам проблем с log-ването на user. Дали бихте хвърлили един поглед на проекта ми и къде допускам грешка. Благодаря предварително
https://github.com/ViliqnVachev/pleten-chaos

**Comment by luchob** [comment]
Здрасти!

Ами тъй е - като казвах аз да се гледа какво минава в HTTP заявките на първо време... ;-)

<img width="1397" alt="Screenshot 2022-06-11 at 10 35 34" src="https://user-images.githubusercontent.com/10339738/173178405-aaf5a0b8-d429-4db1-8f79-d6009d9fed5f.png">

Полето ти за паролата се казва "pass", а не "password" както си задал в конфигурацията:

```	
passwordParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY)
```

И между другото - виж тук - https://github.com/luchob/softuni-may2022/issues/10

Поздрави,
Л.

**Comment by luchob** [comment]
И в допълнение, получих имейл след регистрация, което ме навежда на мисълта че си комитнал някаква парола за SMTP сървър ;-)
